### ISSUE TITLE
Multiple pattern files

### ISSUE THREAD

**Issue by Yago** [digitalocean/heartbot#2]
Hi ! First, I would like to say that your Hubot module is great :+1: 

After writting some new patterns, my config file start to be really huge... What do you think of having multiple pattern files. Something like (in `heartbot.config.yml`) : 

``` yaml

---
probability: 1
patterns:
  - ./patterns/love.yml
  - ./patterns/forecast.yml
  - ./patterns/coffee-maker.yml
```

We can simply loop over those file to return all the patterns. 

And what about having an `events` option ?

``` yaml
events: ./events/
```

If you want, I can do a pull request to help you :wink:
